id: P007895
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD190
  title: རྒྱལ་མཁན་པོ་གྲགས་པ་རྒྱལ་མཚན་གྱི་སྙན་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    222b4eb50a704570872c0dc302948ac9:
      image_group_id: I4PD4670
      title: ''
      volume_number: 1
      total_pages: 720
ebook_metadata:
  title: རྒྱལ་མཁན་པོ་གྲགས་པ་རྒྱལ་མཚན་གྱི་སྙན་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007895
  cover: cover.jpg
  layers:
  - pagination
